import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='w-full bg-white h-12 flex justify-between items-center my-4'>
          <a href="/" className='text-black'>OG bro</a>
          <a href="/roulette" className='text-black'>dinner spinner</a>
        </nav>
        <section>{children}</section>
        </body>
    </html>
  )
}
